name: test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: actions/setup-java@v4.3.0
      with:
        java-version: 22
        distribution: temurin
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sbt test
